sudo: required

services:
  - docker

script:
  # Check if formatting is required
  - ./build.sh host catkin_make --make-args clangformat-check

  # Run pylint
  - ./build.sh host --make-args pylint

  # Check if the code builds using both toolchains
  - ./build.sh host
  - ./build.sh jetson
