sudo: required

services:
  - docker

script:
  # Check if formatting is required
  - ./build.sh host catkin_make --make-args clangformat-check

  # Run pylint
  - ./build.sh host --make-args pylint

  # Check if the code builds
  - docker run -it -v $(pwd):/catkin_ws/src/robosub ci_builder catkin_make

  # Run tests
  - docker run -it -v $(pwd):/catkin_ws/src/robosub ci_builder catkin_make run_tests
