sudo: required

services:
  - docker

script:
  # Build containers separately
  - ./tools/docker/build.sh host
  - ./tools/docker/build.sh jetson

  # Check if formatting is required
  - ./build.sh host --make-args clang-format-check

  # Run pylint
  - ./build.sh host --make-args pylint

  # Check if the code builds using both toolchains
  - ./build.sh host
  - ./build.sh jetson
