sudo: required

services:
  - docker

script:
  - docker pull illinoisauv/robosub:latest
  # Check if formatting is required
  - ./build.sh host --make-args clang-format-check

  # Run pylint
  - ./build.sh host --make-args pylint

  # Check if the code builds
  - ./build.sh host
