---
- hosts: jetson
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: installed
      become: true
      with_items:
        - ros-kinetic-mavros
        - ros-kinetic-gscam
