---
- hosts: jetson
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: installed
      become: true
      with_items:
        - gstreamer1.0-tools
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libgstreamer-plugins-good1.0-dev

    - name: Create catkin workspace
      file:
        path: ~/gscam_ws/src
        state: directory

    - name: Create catkin workspace
      git:
        repo: https://github.com/ros-drivers/gscam
        clone: yes
        dest: ~/gscam_ws/src/gscam

    - name: Run catkin_make
      shell: bash -ic "catkin_make install -DGSTREAMER_VERSION_1_x=On"
      args:
        chdir: ~/gscam_ws
        creates: ~/gscam_ws/build/CMakeCache.txt # Only run if CMakeCache doesn't already exist

    - name: Source gscam setup.bash in bashrc
      lineinfile:
        create: yes
        state: present
        line: "source ~/gscam_ws/devel/setup.bash"
        path: ~/.bashrc
