---
- hosts: jetson
  tasks:
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: "ALL ALL = (ALL) NOPASSWD: ALL"
        state: present
      become: true


- import_playbook: install-general.yml
- import_playbook: install-key.yml
- import_playbook: install-networking.yml
- import_playbook: install-cuda.yml
- import_playbook: install-ros.yml
- import_playbook: install-packages.yml
- import_playbook: install-udev.yml
- import_playbook: install-tiscamera.yml
- import_playbook: setup-catkin.yml
- import_playbook: install-zed.yml
- import_playbook: install-gscam.yml
