---
- hosts: jetson
  tasks:
    - name: Disable apt-daily.timer
      systemd:
        name: apt-daily.timer
        state: stopped
        enabled: no
      become: true
    - name: Disable apt-daily-upgrade.timer
      systemd:
        name: apt-daily-upgrade.timer
        state: stopped
        enabled: no
      become: true

    - name: Install resolvconf
      apt:
        name: resolvconf
        state: installed
      become: true
