---
- hosts: jetson
  tasks:
    - name: Install zed-ros-wrapper dependencies libpcl1
      apt:
        name: libpcl1
      become: true

    - name: Install zed-ros-wrapper dependencies ros-kinetic-pcl-ros
      apt:
        name: ros-kinetic-pcl-ros
      become: true

    - name: Download sdk
      get_url:
        url: 'https://download.stereolabs.com/zedsdk/2.3/tegrax2_jp31'
        dest: /tmp/ZED_SDK.run

    - name: Make installer executable
      file:
        path: /tmp/ZED_SDK.run
        mode: +x

    - name: Install zed sdk
      command: /tmp/ZED_SDK.run --quiet -- silent

    - name: Chown zed sdk files
      file:
        path: /usr/local/zed
        owner: "{{ ansible_user_id }}"
        recurse: yes
      become: true

    - name: Create catkin workspace
      file:
        path: ~/zed_ws/src
        state: directory

    - name: Download ros package
      git:
        clone: yes
        dest: ~/zed_ws/src/zed-ros-wrapper
        repo: https://github.com/stereolabs/zed-ros-wrapper

    - name: Run catkin_make
      shell: bash -ic "catkin_make"
      args:
        chdir: /home/ubuntu/zed_ws

    - name: Run catkin_make install
      shell: bash -ic "catkin_make install -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic"
      args:
        chdir: /home/ubuntu/zed_ws
      become: true

    # - name: Source zed setup.bash in bashrc
    #   lineinfile:
    #     create: yes
    #     state: present
    #     line: "source ~/zed_ws/install/setup.bash"
    #     path: ~/.bashrc
