---
- hosts: jetson
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: installed
      become: true
      with_items:
        - ros-kinetic-mavros
        - ros-kinetic-gscam
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-bad

    - name: Install geographiclib database
      shell: /opt/ros/kinetic/lib/mavros/install_geographiclib_datasets.sh
      become: true
