---
- hosts: jetson
  tasks:
    - name: Create catkin_ws
      file:
        state: directory
        recurse: yes
        path: /home/ubuntu/catkin_ws/src

    - name: Source devel/setup.bash in bashrc
      lineinfile:
        create: yes
        state: present
        line: "source ~/catkin_ws/devel/setup.bash"
        path: ~/.bashrc
